package gogen

import (
	"fmt"
	"strings"
)

// Emit holds the generated file contents for one entity.
type Emit struct {
	GoFile  string // {table}.go
	SQLFile string // {table}.sql
}

// Generate produces Go + SQL output for a single entity.
// pkg is the Go package name to emit (e.g. "store").
func Generate(e *EntitySchema, pkg string) Emit {
	return Emit{
		GoFile:  emitGo(e, pkg),
		SQLFile: emitSQL(e),
	}
}

func emitGo(e *EntitySchema, pkg string) string {
	var b strings.Builder

	typeName := CamelCase(e.Meta.Title)

	// Determine imports from field types. UUID always needed (primary key).
	needsTime, needsUUID, needsJSON := false, true, false
	for _, f := range append(e.RequiredFields, e.OptionalFields...) {
		switch GoType(f.Type) {
		case "time.Time":
			needsTime = true
		case "json.RawMessage":
			needsJSON = true
		}
	}

	fmt.Fprintf(&b, "// Code generated by lw codegen go from %s. DO NOT EDIT.\n\n", e.Meta.SchemaID)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	// Imports — std block, then external block
	var stdParts, extParts []string
	if needsJSON {
		stdParts = append(stdParts, `"encoding/json"`)
	}
	if needsTime {
		stdParts = append(stdParts, `"time"`)
	}
	if needsUUID {
		extParts = append(extParts, `"github.com/google/uuid"`)
	}
	if len(stdParts) > 0 || len(extParts) > 0 {
		b.WriteString("import (\n")
		for _, s := range stdParts {
			fmt.Fprintf(&b, "\t%s\n", s)
		}
		if len(stdParts) > 0 && len(extParts) > 0 {
			b.WriteString("\n")
		}
		for _, s := range extParts {
			fmt.Fprintf(&b, "\t%s\n", s)
		}
		b.WriteString(")\n\n")
	}

	fmt.Fprintf(&b, "// %s is generated from %s.\n", typeName, e.Meta.SchemaID)
	fmt.Fprintf(&b, "type %s struct {\n", typeName)
	fmt.Fprintf(&b, "\tID\t\t\tuuid.UUID\t`db:\"id\" json:\"id\"`\n")

	for _, f := range e.RequiredFields {
		if f.Storage != "db" {
			continue
		}
		gt := GoType(f.Type)
		fmt.Fprintf(&b, "\t%s\t\t%s\t`db:%q json:%q`\n", CamelCase(f.Name), gt, f.Name, f.Name)
	}
	for _, f := range e.OptionalFields {
		if f.Storage != "db" {
			continue
		}
		gt := GoType(f.Type)
		if gt != "json.RawMessage" {
			gt = "*" + gt
		}
		fmt.Fprintf(&b, "\t%s\t\t%s\t`db:%q json:%q`\n", CamelCase(f.Name), gt, f.Name, f.Name+",omitempty")
	}

	b.WriteString("}\n")
	return b.String()
}

func emitSQL(e *EntitySchema) string {
	var b strings.Builder

	fmt.Fprintf(&b, "-- Code generated by lw codegen go from %s. DO NOT EDIT.\n\n", e.Meta.SchemaID)
	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", e.Meta.TableName)
	fmt.Fprintf(&b, "\tid\t\t\t\tUUID\t\tNOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,\n")

	type colEntry struct {
		f        FieldDef
		required bool
	}
	var cols []colEntry
	for _, f := range dbOnly(e.RequiredFields) {
		cols = append(cols, colEntry{f, true})
	}
	for _, f := range dbOnly(e.OptionalFields) {
		cols = append(cols, colEntry{f, false})
	}
	for i, c := range cols {
		comma := ","
		if i == len(cols)-1 {
			comma = ""
		}
		sqlType := SQLType(c.f.Type, c.f.ColumnType)
		extra := fkClause(e, c.f, c.required)
		if c.required {
			extra = " NOT NULL" + extra
		}
		fmt.Fprintf(&b, "\t%-28s%-14s%s%s\n", c.f.Name, sqlType, extra, comma)
	}

	b.WriteString(");\n\n")

	// Indexes on indexed fields
	for _, f := range append(e.RequiredFields, e.OptionalFields...) {
		if f.Indexed {
			fmt.Fprintf(&b, "CREATE INDEX IF NOT EXISTS %s_%s_idx ON %s (%s);\n",
				e.Meta.TableName, f.Name, e.Meta.TableName, f.Name)
		}
	}

	fmt.Fprintf(&b, "\nALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", e.Meta.TableName)
	return b.String()
}

func dbOnly(fields []FieldDef) []FieldDef {
	var out []FieldDef
	for _, f := range fields {
		if f.Storage == "db" {
			out = append(out, f)
		}
	}
	return out
}

// fkClause builds the REFERENCES … ON DELETE … clause for a FK field.
// For required parent FKs, the on_delete action comes from relations.parent_fk.
func fkClause(e *EntitySchema, f FieldDef, required bool) string {
	if f.FKRef == "" || f.FKColumn == "" {
		return ""
	}
	onDelete := "SET NULL"
	if required {
		if e.Relations.ParentFK.Column == f.Name && e.Relations.ParentFK.OnDelete != "" {
			onDelete = strings.ToUpper(e.Relations.ParentFK.OnDelete)
		} else {
			onDelete = "CASCADE"
		}
	}
	return fmt.Sprintf(" REFERENCES %s(%s) ON DELETE %s", TableFromFKRef(f.FKRef), f.FKColumn, onDelete)
}
