package gogen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// GenerateGo renders the Go struct for a single entity. pkg is the package
// name to emit (e.g. "store"). Every table is multi-tenant: the struct carries
// ID and TenantID ahead of the schema fields (ADR-0010 shared-schema + RLS).
// Returns an error rather than writing uncompilable source if the result fails
// to parse (lightwave-cli#227).
func GenerateGo(e *EntitySchema, pkg string) (string, error) {
	var b strings.Builder

	typeName := CamelCase(e.Meta.Title)

	// Determine imports from field types. UUID always needed (id + tenant_id).
	needsTime, needsUUID, needsJSON := false, true, false

	for _, f := range append(e.RequiredFields, e.OptionalFields...) {
		switch GoType(f.Type) {
		case "time.Time":
			needsTime = true
		case "json.RawMessage":
			needsJSON = true
		}
	}

	fmt.Fprintf(&b, "// Code generated by lw codegen go from %s. DO NOT EDIT.\n\n", e.Meta.SchemaID)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	// Emit needed imports in one block; go/format (below) sorts them.
	var imports []string

	if needsJSON {
		imports = append(imports, `"encoding/json"`)
	}

	if needsTime {
		imports = append(imports, `"time"`)
	}

	if needsUUID {
		imports = append(imports, `"github.com/google/uuid"`)
	}

	if len(imports) > 0 {
		b.WriteString("import (\n\t" + strings.Join(imports, "\n\t") + "\n)\n\n")
	}

	fmt.Fprintf(&b, "// %s is generated from %s.\n", typeName, e.Meta.SchemaID)
	fmt.Fprintf(&b, "type %s struct {\n", typeName)
	fmt.Fprintf(&b, "\tID\t\tuuid.UUID\t`db:\"id\" json:\"id\"`\n")
	fmt.Fprintf(&b, "\tTenantID\tuuid.UUID\t`db:\"tenant_id\" json:\"tenant_id\"`\n")

	for _, f := range e.RequiredFields {
		if f.Storage != "db" {
			continue
		}

		fmt.Fprintf(&b, "\t%s\t\t%s\t`db:%q json:%q`\n", CamelCase(f.Name), GoType(f.Type), f.Name, f.Name)
	}

	for _, f := range e.OptionalFields {
		if f.Storage != "db" {
			continue
		}

		gt := GoType(f.Type)
		if gt != "json.RawMessage" {
			gt = "*" + gt
		}

		fmt.Fprintf(&b, "\t%s\t\t%s\t`db:%q json:%q`\n", CamelCase(f.Name), gt, f.Name, f.Name+",omitempty")
	}

	b.WriteString("}\n")

	// gofmt the result so generated structs pass `gofmt -l` / go build with
	// correct column alignment (lightwave-cli#227 P2-6). A parse failure is a
	// real bug (e.g. a malformed identifier) — surface it instead of writing
	// uncompilable source.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting generated Go for %s: %w", typeName, err)
	}

	return string(formatted), nil
}

// EmitMigration renders ONE PostgreSQL migration for the whole entity set:
// tables in FK-topological order (parents first), each shared-schema
// multi-tenant (tenant_id + RLS isolation policy + FORCE), then all RLS
// statements. Depends on 001_init.sql (the tenants table); apply after it.
//
// A single ordered file is required because the platform's db.Migrate applies
// files lexically — per-table files would run epics before prds and fail the
// cross-table FKs (lightwave-cli#227 P0-2).
func EmitMigration(entities []*EntitySchema) (string, error) {
	ordered := topoSort(entities)

	known := map[string]bool{"tenants": true}
	for _, e := range entities {
		known[e.Meta.TableName] = true
	}

	var b strings.Builder

	b.WriteString("-- Code generated by lw codegen go. DO NOT EDIT.\n")
	b.WriteString("-- Depends on 001_init.sql (tenants table); apply after it.\n\n")
	b.WriteString("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";\n\n")

	for _, e := range ordered {
		b.WriteString(createTable(e, known))
		b.WriteString("\n")
	}

	for _, e := range ordered {
		for _, idx := range indexLines(e) {
			b.WriteString(idx)
		}
	}

	b.WriteString("\n")

	for _, e := range ordered {
		t := e.Meta.TableName
		fmt.Fprintf(&b, "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", t)
		fmt.Fprintf(&b, "ALTER TABLE %s FORCE ROW LEVEL SECURITY;\n", t)
	}

	b.WriteString("\n")

	for _, e := range ordered {
		t := e.Meta.TableName
		fmt.Fprintf(&b, "CREATE POLICY %s_tenant_isolation ON %s\n    USING (tenant_id::text = current_setting('app.current_org', true));\n", t, t)
	}

	return b.String(), nil
}

// createTable renders one CREATE TABLE: id PK, tenant_id (FK to tenants), the
// schema's db columns, a PER-TENANT UNIQUE on the natural key, and tenant-
// scoped composite FKs. UNIQUE (tenant_id, slug) + FOREIGN KEY (tenant_id, ref)
// → parent(tenant_id, slug) keep natural keys unique and referential integrity
// WITHIN a tenant (ADR-0010, mirroring 001_init.sql) — a global UNIQUE(slug)
// would collide/leak across tenants and let FKs cross tenant boundaries
// (lightwave-cli#227 P0-2).
func createTable(e *EntitySchema, known map[string]bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", e.Meta.TableName)

	cols := []string{
		"id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY",
		"tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE",
	}

	reqDB := dbOnly(e.RequiredFields)
	for i := range reqDB {
		cols = append(cols, columnDef(&reqDB[i], true))
	}

	optDB := dbOnly(e.OptionalFields)
	for i := range optDB {
		cols = append(cols, columnDef(&optDB[i], false))
	}

	if e.NaturalKey.Column != "" && e.NaturalKey.Unique {
		cols = append(cols, fmt.Sprintf("UNIQUE (tenant_id, %s)", e.NaturalKey.Column))
	}

	cols = append(cols, foreignKeys(e, known)...)

	b.WriteString("\t" + strings.Join(cols, ",\n\t") + "\n);\n")

	return b.String()
}

// columnDef builds one column definition: type, null-ness, and DEFAULT now()
// on timestamps. UNIQUE and FK constraints are emitted table-level (composite
// with tenant_id) by createTable / foreignKeys, not here.
func columnDef(f *FieldDef, required bool) string {
	parts := []string{f.Name, SQLType(f.Type, f.ColumnType)}

	if required {
		parts = append(parts, "NOT NULL")
	}

	if (f.Name == "created_at" || f.Name == "updated_at") && f.Type == "datetime" {
		parts = append(parts, "DEFAULT now()")
	}

	return strings.Join(parts, " ")
}

func indexLines(e *EntitySchema) []string {
	var out []string

	for _, f := range append(e.RequiredFields, e.OptionalFields...) {
		if f.Indexed {
			out = append(out, fmt.Sprintf("CREATE INDEX IF NOT EXISTS %s_%s_idx ON %s (%s);\n",
				e.Meta.TableName, f.Name, e.Meta.TableName, f.Name))
		}
	}

	return out
}

func dbOnly(fields []FieldDef) []FieldDef {
	out := make([]FieldDef, 0, len(fields))

	for _, f := range fields {
		if f.Storage == "db" {
			out = append(out, f)
		}
	}

	return out
}

// foreignKeys emits tenant-scoped composite FK constraints for fields whose
// fk_ref resolves to a table in the known set (an out-of-set ref is skipped, so
// the migration never references a relation it doesn't create). The declared
// parent FK uses its schema-declared on_delete; every other FK uses NO ACTION
// (the default) — a composite FK that includes the NOT NULL tenant_id cannot
// use SET NULL, and the schemas never declared CASCADE for non-parent refs.
func foreignKeys(e *EntitySchema, known map[string]bool) []string {
	var out []string

	for _, group := range [][]FieldDef{dbOnly(e.RequiredFields), dbOnly(e.OptionalFields)} {
		for i := range group {
			f := &group[i]
			if f.FKRef == "" || f.FKColumn == "" {
				continue
			}

			target := TableFromFKRef(f.FKRef)
			if !known[target] {
				continue
			}

			clause := fmt.Sprintf("FOREIGN KEY (tenant_id, %s) REFERENCES %s(tenant_id, %s)", f.Name, target, f.FKColumn)
			if e.Relations.ParentFK.Column == f.Name && e.Relations.ParentFK.OnDelete != "" {
				clause += " ON DELETE " + strings.ToUpper(e.Relations.ParentFK.OnDelete)
			}

			out = append(out, clause)
		}
	}

	return out
}

// topoSort orders entities so a table's FK parents are created before it.
// Self-references are ignored (valid within a single CREATE TABLE) and any
// cross-table cycle is broken best-effort. Deterministic: ties resolve by
// table name so golden output is stable.
func topoSort(entities []*EntitySchema) []*EntitySchema {
	byTable := make(map[string]*EntitySchema, len(entities))
	names := make([]string, 0, len(entities))

	for _, e := range entities {
		byTable[e.Meta.TableName] = e
		names = append(names, e.Meta.TableName)
	}

	sort.Strings(names)

	const (
		visiting = 1
		done     = 2
	)

	state := make(map[string]int, len(entities))
	ordered := make([]*EntitySchema, 0, len(entities))

	var visit func(e *EntitySchema)

	visit = func(e *EntitySchema) {
		if state[e.Meta.TableName] != 0 {
			return // done, or visiting (cycle) — break
		}

		state[e.Meta.TableName] = visiting

		for _, dep := range referencedTables(e) {
			if dep == e.Meta.TableName {
				continue // self-ref is valid in one CREATE TABLE
			}

			if parent, ok := byTable[dep]; ok {
				visit(parent)
			}
		}

		state[e.Meta.TableName] = done
		ordered = append(ordered, e)
	}

	for _, n := range names {
		visit(byTable[n])
	}

	return ordered
}
