package cli

import (
	"context"
	"errors"
	"fmt"
)

// Schema-driven schema handlers. commands.yaml v3.0.0 declares 5 commands:
// validate, drift, reconcile, generate, coverage.
//
// Most delegate to Django management commands in lightwave-core/schema
// (validate_schema, drift_report, reconcile). `generate` is a stub until
// codegen targets are formalized as a single management entrypoint;
// `coverage` reuses the brain SST coverage walker from sst.go.

func init() {
	RegisterHandler("schema.validate", schemaValidateHandler)
	RegisterHandler("schema.drift", schemaDriftHandler)
	RegisterHandler("schema.reconcile", schemaReconcileHandler)
	RegisterHandler("schema.generate", schemaGenerateHandler)
	RegisterHandler("schema.coverage", schemaCoverageHandler)
}

func schemaValidateHandler(_ context.Context, _ []string, _ map[string]any) error {
	return errDjangoRetired("schema validate", "This validated Django model state against the YAML stamp. `lw check schema` is a DIFFERENT check — it compares the CLI command surface to its handlers — so it is not the replacement. No lw verb validates data schemas against the stamp yet.")
}

func schemaDriftHandler(_ context.Context, _ []string, _ map[string]any) error {
	return errDjangoRetired("schema drift", "This diffed the Django DB against the YAML stamp. Note the name collision: `lw check schema` is the CLI-surface drift gate, not this. No lw verb reports data-schema drift yet.")
}

func schemaReconcileHandler(_ context.Context, _ []string, _ map[string]any) error {
	return errDjangoRetired("schema reconcile", "This mutated Django schema rows to match the YAML ideal. The Go stack generates its DDL instead: `lw codegen go` emits schema.sql whole, so there is nothing to reconcile row-by-row.")
}

// schemaGenerateHandler is a thin shim — codegen entrypoints currently live
// in `lw codegen` (Go-native) and the SST `_codegen` block. Surface the gap.
func schemaGenerateHandler(_ context.Context, args []string, _ map[string]any) error {
	if len(args) < 1 {
		return errors.New("usage: lw schema generate <go|python>")
	}

	return fmt.Errorf("schema generate %s: not yet wired (use `lw codegen` for Go registry; Pydantic is generated by lightwave-core build)", args[0])
}

// schemaCoverageHandler reuses the existing `lw sst coverage` walker by
// invoking runSSTCoverage's logic. Sets the JSON flag from the dispatcher
// flag map so output stays agent-friendly.
func schemaCoverageHandler(_ context.Context, _ []string, flags map[string]any) error {
	sstCoverageJSON = flagBool(flags, "json")
	return runSSTCoverage(nil, nil)
}
