package cli

import (
	"context"
	"fmt"
)

// Schema-driven schema handlers. commands.yaml v3.0.0 declares 5 commands:
// validate, drift, reconcile, generate, coverage.
//
// Most delegate to Django management commands in lightwave-core/schema
// (validate_schema, drift_report, reconcile). `generate` is a stub until
// codegen targets are formalized as a single management entrypoint;
// `coverage` reuses the brain SST coverage walker from sst.go.

func init() {
	RegisterHandler("schema.validate", schemaValidateHandler)
	RegisterHandler("schema.drift", schemaDriftHandler)
	RegisterHandler("schema.reconcile", schemaReconcileHandler)
	RegisterHandler("schema.generate", schemaGenerateHandler)
	RegisterHandler("schema.coverage", schemaCoverageHandler)
}

func schemaValidateHandler(ctx context.Context, _ []string, flags map[string]any) error {
	args := []string{"validate_schema"}
	if flagBool(flags, "strict") {
		args = append(args, "--strict")
	}
	if flagBool(flags, "fix") {
		args = append(args, "--fix")
	}
	if flagBool(flags, "json") {
		args = append(args, "--json")
	}
	return djangoManage(ctx, args...)
}

func schemaDriftHandler(ctx context.Context, _ []string, flags map[string]any) error {
	args := []string{"drift_report"}
	if out := flagStr(flags, "output"); out != "" {
		args = append(args, "--output", out)
	}
	if flagBool(flags, "json") {
		args = append(args, "--json")
	}
	return djangoManage(ctx, args...)
}

func schemaReconcileHandler(ctx context.Context, _ []string, flags map[string]any) error {
	if !flagBool(flags, "yes") && !flagBool(flags, "dry-run") {
		if !promptYesNo("Reconcile DB to YAML ideal state? Mutates schema rows.") {
			fmt.Println("Cancelled")
			return nil
		}
	}
	args := []string{"reconcile"}
	if flagBool(flags, "dry-run") {
		args = append(args, "--check")
	}
	return djangoManage(ctx, args...)
}

// schemaGenerateHandler is a thin shim — codegen entrypoints currently live
// in `lw codegen` (Go-native) and the SST `_codegen` block. Surface the gap.
func schemaGenerateHandler(_ context.Context, args []string, _ map[string]any) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: lw schema generate <go|python>")
	}
	return fmt.Errorf("schema generate %s: not yet wired (use `lw codegen` for Go registry; Pydantic is generated by lightwave-core build)", args[0])
}

// schemaCoverageHandler reuses the existing `lw sst coverage` walker by
// invoking runSSTCoverage's logic. Sets the JSON flag from the dispatcher
// flag map so output stays agent-friendly.
func schemaCoverageHandler(_ context.Context, _ []string, flags map[string]any) error {
	sstCoverageJSON = flagBool(flags, "json")
	return runSSTCoverage(nil, nil)
}
