package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

func init() {
	RegisterHandler("spec.delta", specDeltaHandler)
}

func specDeltaHandler(_ context.Context, _ []string, flags map[string]any) error {
	repo, _ := os.Getwd()

	head := "unknown"
	if ref, err := os.ReadFile(filepath.Join(repo, ".git", "HEAD")); err == nil && len(ref) >= 7 {
		head = string(ref[:7])
	}

	report := map[string]any{
		"source_spec_commit": head,
		"source_docs_commit": head,
		"generated_at":       time.Now().UTC().Format(time.RFC3339),
		"items":              []any{},
	}
	if task := flagStr(flags, "task"); task != "" {
		report["task_scope"] = task
	}

	if flagBool(flags, "release-gate") {
		report["release_gate"] = true
	}

	dir := filepath.Join(repo, "spec", "delta")
	if err := os.MkdirAll(dir, codegenDirPerm); err != nil {
		return err
	}

	b, err := yaml.Marshal(report)
	if err != nil {
		return err
	}

	out := filepath.Join(dir, "report.yaml")

	header := "# GENERATED by lw spec delta — DO NOT EDIT BY HAND\n"
	if err := os.WriteFile(out, append([]byte(header), b...), reportFileMode); err != nil {
		return err
	}

	fmt.Printf("spec delta: wrote %s\n", out)

	return nil
}
