package zodgen

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

const generatedHeader = "// GENERATED by `lw codegen types` — do not edit.\n// Source: lightwave-core src/schemas/data/ui + data/enums (ADR-0006).\n"

// maxPropTypeDepth bounds prop_types reference expansion; deeper nesting
// almost certainly means a reference cycle in the instance YAML.
const maxPropTypeDepth = 8

// EmitEnums renders enums.generated.ts: one z.enum per ui_* stamp that
// declares a typescript: target, plus the inferred type alias. Stamps
// without a typescript target are skipped (they exist for other bindings).
func EmitEnums(enums map[string]*EnumStamp) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("import { z } from \"zod\";\n")

	for _, name := range sortedKeys(enums) {
		e := enums[name]

		tsName := TSName(e.Meta.Generates)
		if tsName == "" {
			continue
		}

		values := make([]string, len(e.Options))
		for i, o := range e.Options {
			values[i] = fmt.Sprintf("%q", o.Value)
		}

		b.WriteString("\n")
		fmt.Fprintf(&b, "// %s (%s)\n", e.Meta.Title, name)
		fmt.Fprintf(&b, "export const %s = z.enum([%s]);\n", tsName, strings.Join(values, ", "))
		fmt.Fprintf(&b, "export type %s = z.infer<typeof %s>;\n", tsName, tsName)
	}

	return b.String()
}

// EmitSections renders sections.generated.ts: one Zod object per section
// instance plus a registry keyed by "<family>/<variant>" — a drop-in
// replacement for a hand-written sectionSchemas registry (the joelschaeffer-
// site src/data/sections.ts shape). Nested prop_types are expanded INLINE at
// their reference site, matching the hand-written registry style and
// avoiding cross-section const name collisions.
func EmitSections(instances []*SectionInstance) (string, error) {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("import { z } from \"zod\";\n\n")

	registry := make([]string, 0, len(instances))
	for _, inst := range instances {
		constName := tsIdentifier(inst.Variant)

		obj, err := zodObject(inst.Props, inst.PropTypes, 0)
		if err != nil {
			return "", fmt.Errorf("section %s: %w", inst.Key, err)
		}

		fmt.Fprintf(&b, "// %s — %s\n", inst.Key, inst.Title)
		fmt.Fprintf(&b, "export const %s = %s;\n\n", constName, obj)
		registry = append(registry, fmt.Sprintf("    %q: %s,", inst.Key, constName))
	}

	b.WriteString("export const sectionSchemas: Record<string, z.ZodType> = {\n")
	b.WriteString(strings.Join(registry, "\n"))
	b.WriteString("\n};\n")

	return b.String(), nil
}

// zodObject renders z.object({...}) for a field list, expanding PascalCase
// type references inline from propTypes. depth guards reference cycles.
func zodObject(fields []FieldDecl, propTypes map[string][]FieldDecl, depth int) (string, error) {
	if depth > maxPropTypeDepth {
		return "", errors.New("prop_types nesting exceeds max depth (reference cycle?)")
	}

	entries := make([]string, 0, len(fields))

	for _, f := range fields {
		expr, err := zodExpr(f.Type, f.Options, propTypes, depth)
		if err != nil {
			return "", fmt.Errorf("field %s: %w", f.Name, err)
		}

		if f.Nullable {
			expr += ".nullable()"
		}

		if f.Default != nil {
			expr += fmt.Sprintf(".default(%s)", tsLiteral(f.Default))
		}

		if !f.Required {
			expr += ".optional()"
		}

		entries = append(entries, fmt.Sprintf("%s: %s", f.Name, expr))
	}

	return "z.object({ " + strings.Join(entries, ", ") + " })", nil
}

// zodExpr maps one SST type expression to a Zod expression.
//
// Grammar: str | int | float | bool | date | enum | dict | list[X] |
// dict[str, X] | PascalCaseRef. date maps to z.string() because consuming
// sites pass ISO strings; timestamps are declared str in the stamp with the
// z.string().datetime() mapping documented there (ADR-0006) — that refinement
// lands with contract-shape emission, not section props.
func zodExpr(t string, options []string, propTypes map[string][]FieldDecl, depth int) (string, error) {
	switch {
	case t == "str" || t == "date":
		return "z.string()", nil
	case t == "int":
		return "z.number().int()", nil
	case t == "float":
		return "z.number()", nil
	case t == "bool":
		return "z.boolean()", nil
	case t == "enum":
		if len(options) == 0 {
			return "", errors.New("enum without options (values_ref resolution happens at load time)")
		}

		vals := make([]string, len(options))
		for i, v := range options {
			vals[i] = fmt.Sprintf("%q", v)
		}

		return fmt.Sprintf("z.enum([%s])", strings.Join(vals, ", ")), nil
	case t == "dict":
		return "z.record(z.string(), z.unknown())", nil
	case strings.HasPrefix(t, "list[") && strings.HasSuffix(t, "]"):
		inner, err := zodExpr(strings.TrimSuffix(strings.TrimPrefix(t, "list["), "]"), nil, propTypes, depth)
		if err != nil {
			return "", err
		}

		return fmt.Sprintf("z.array(%s)", inner), nil
	case strings.HasPrefix(t, "dict[str, ") && strings.HasSuffix(t, "]"):
		inner, err := zodExpr(strings.TrimSuffix(strings.TrimPrefix(t, "dict[str, "), "]"), nil, propTypes, depth)
		if err != nil {
			return "", err
		}

		return fmt.Sprintf("z.record(z.string(), %s)", inner), nil
	default:
		// PascalCase reference into prop_types, expanded inline.
		ref, ok := propTypes[t]
		if !ok {
			return "", fmt.Errorf("unknown type %q (no prop_types entry)", t)
		}

		return zodObject(ref, propTypes, depth+1)
	}
}

// tsLiteral renders a YAML scalar as a TypeScript literal.
func tsLiteral(v any) string {
	switch x := v.(type) {
	case string:
		return fmt.Sprintf("%q", x)
	case bool:
		return strconv.FormatBool(x)
	default:
		return fmt.Sprintf("%v", x)
	}
}

// tsIdentifier converts a kebab-case variant to a camelCase TS identifier
// (content-section-split-image-02 → contentSectionSplitImage02).
func tsIdentifier(kebab string) string {
	parts := strings.Split(kebab, "-")

	var b strings.Builder

	for i, p := range parts {
		if p == "" {
			continue
		}

		if i == 0 {
			b.WriteString(p)
			continue
		}

		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}

	return b.String()
}

// ResolveValuesRefs rewrites enum fields that carry values_ref into concrete
// options from the enum stamps, so emission never needs the stamps again.
// Returns an error naming the field when a ref points at a missing stamp —
// silent fallback would emit z.enum([]) and reject everything.
func ResolveValuesRefs(fields []FieldDecl, enums map[string]*EnumStamp) error {
	for i := range fields {
		f := &fields[i]
		if f.ValuesRef == "" {
			continue
		}

		stamp, ok := enums[f.ValuesRef]
		if !ok {
			return fmt.Errorf("field %s: values_ref %q has no enum stamp in data/enums/", f.Name, f.ValuesRef)
		}

		f.Options = make([]string, len(stamp.Options))
		for j, o := range stamp.Options {
			f.Options[j] = o.Value
		}
	}

	return nil
}
