// GENERATED by `lw codegen types` — do not edit.
// Source: lightwave-core src/schemas/data/ui + data/enums (ADR-0006).
import { z } from "zod";

// ── Component Contract ──
export const ComponentContractPropField = z.object({ default: z.string(), description: z.string(), name: z.string(), options: z.array(z.string()), required: z.boolean().default(false), type: z.string() });
export const ComponentContract = z.object({ name: z.string(), category: z.enum(["base", "application", "marketing", "foundations", "shared-assets", "emails"]) });
export type ComponentContract = z.infer<typeof ComponentContract>;

// ── Section Contract ──
export const SectionContractPropField = z.object({ default: z.string(), description: z.string(), name: z.string(), options: z.array(z.string()), required: z.boolean().default(false), type: z.string() });
export const SectionContract = z.object({ key: z.string(), family: z.enum(["header-section", "header-navigation", "content", "footers", "blog", "store", "photography"]), variant: z.string(), title: z.string(), props: z.array(SectionContractPropField) });
export type SectionContract = z.infer<typeof SectionContract>;

// ── Page Definition ──
export const PageDefinitionLegalMeta = z.object({ effective_date: z.string(), jurisdiction: z.string(), last_reviewed: z.string().nullable(), required_blocks: z.array(z.string()) });
export const PageDefinitionSectionRef = z.object({ props: z.record(z.string(), z.unknown()), section: z.string() });
export const PageDefinitionSeo = z.object({ description: z.string(), no_index: z.boolean().default(false), og_image: z.string().nullable(), title: z.string() }).superRefine((v, ctx) => {
  if (v.og_image != null && !(v.og_image.startsWith("https://") || v.og_image.startsWith("/"))) {
    ctx.addIssue({ code: "custom", path: ["og_image"], message: "og_image must be an absolute https URL or a media-base-relative path beginning with /" });
  }
});
export const PageDefinition = z.object({ slug: z.string(), title: z.string(), page_type: z.enum(["marketing", "legal", "admin", "app"]), sections: z.array(PageDefinitionSectionRef), seo: PageDefinitionSeo, legal: PageDefinitionLegalMeta.nullable().optional(), collection: z.string().nullable().optional() }).superRefine((v, ctx) => {
  if (v.page_type === "legal" && v.legal == null) {
    ctx.addIssue({ code: "custom", path: ["legal"], message: "legal pages require LegalMeta (jurisdiction, effective_date, required_blocks)" });
  }
});
export type PageDefinition = z.infer<typeof PageDefinition>;

// ── Site Config ──
export const SiteConfigBrand = z.object({ logo_dark: z.string().nullable(), logo_light: z.string().nullable(), tokens: z.record(z.string(), z.string()) }).superRefine((v, ctx) => {
  for (const [key, value] of Object.entries(v.tokens)) {
    if (!/^--[a-z][a-z0-9-]*$/.test(key)) {
      ctx.addIssue({ code: "custom", path: ["tokens", key], message: "token keys must match ^--[a-z][a-z0-9-]*$" });
    }
    if (/(url|expression|image-set|var)\s*\(/i.test(value)) {
      ctx.addIssue({ code: "custom", path: ["tokens", key], message: "token values must not contain CSS function calls (injection guard)" });
    }
  }
});
export const SiteConfigComponentPin = z.object({ kind: z.enum(["component", "section"]), lightwave_ui_version: z.string(), name: z.string(), synced_at: z.string().datetime() });
export const SiteConfigDataSources = z.object({ copy_source: z.string(), media_base: z.string() });
export const SiteConfigNavItem = z.object({ href: z.string(), label: z.string() });
export const SiteConfigUiRelease = z.object({ components: z.array(SiteConfigComponentPin).min(1), lightwave_ui_version: z.string() });
export const SiteConfig = z.object({ domain: z.string(), site_name: z.string(), brand: SiteConfigBrand, nav: z.array(SiteConfigNavItem), pages: z.array(z.string()), data_sources: SiteConfigDataSources, ui_release: SiteConfigUiRelease, tenant: z.string().nullable().optional(), locale: z.string().default("en-GB").optional() });
export type SiteConfig = z.infer<typeof SiteConfig>;

// ── App Shell ──
export const AppShellAuth = z.object({ posture: z.enum(["public", "authenticated", "admin"]), provider: z.string().nullable() });
export const AppShell = z.object({ name: z.string(), kind: z.enum(["website", "app", "admin"]), router: z.enum(["react-router", "tanstack-router", "none"]), providers: z.array(z.string()), auth: AppShellAuth.nullable().optional(), site_config: z.string().nullable().optional() }).superRefine((v, ctx) => {
  if (v.kind === "website" && v.site_config == null) {
    ctx.addIssue({ code: "custom", path: ["site_config"], message: "website shells require a site_config reference" });
  }
});
export type AppShell = z.infer<typeof AppShell>;
