// GENERATED by `lw codegen types` — do not edit.
// Source: lightwave-core src/schemas/data/ui + data/enums (ADR-0006).
import { z } from "zod";

// content/content-section-split-image-02 — Content Section — Split Image 02
export const contentSectionSplitImage02 = z.object({ eyebrow: z.string().optional(), title: z.string(), paragraphs: z.array(z.string()).optional(), subheading: z.string().optional(), subheadingParagraphs: z.array(z.string()).optional(), actions: z.array(z.object({ label: z.string(), href: z.string(), color: z.enum(["primary", "secondary"]).optional() })).optional(), image: z.string(), imageAlt: z.string().optional(), imageCaption: z.object({ title: z.string(), role: z.string().optional(), subrole: z.string().optional(), rating: z.number().optional() }).optional() });

export const sectionSchemas: Record<string, z.ZodType> = {
    "content/content-section-split-image-02": contentSectionSplitImage02,
};
