package docsfactory

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// regenerateBody replaces the markdown body below frontmatter with a stub
// synthesized from refresh_source entries. Full symbol extraction is deferred;
// the stub proves the body-regen path is wired for generated kinds.
func regenerateBody(repoRoot, docPath string, kind DocArtifactKind) error {
	if len(kind.RefreshSource) == 0 {
		return nil
	}
	data, err := os.ReadFile(docPath)
	if err != nil {
		return err
	}
	ext := filepath.Ext(docPath)
	if ext != ".md" && ext != ".mdx" {
		return nil
	}

	var sources []string
	for _, rs := range kind.RefreshSource {
		label := rs.Kind
		if rs.Path != "" {
			label = rs.Path
		} else if rs.Glob != "" {
			label = rs.Glob
		}
		sources = append(sources, label)
	}

	body := fmt.Sprintf(`## Generated overview

This document is generated by lw docs sync from:

%s

Do not hand-edit. Fix source code or schemas, then re-run lw docs sync && lw docs render.
`, bulletList(sources))

	fm, err := ParseFrontmatter(data)
	if err != nil {
		return err
	}
	fm.Body = body + "\n"
	out, err := fm.Render()
	if err != nil {
		return err
	}
	return os.WriteFile(docPath, out, 0o644)
}

func bulletList(items []string) string {
	if len(items) == 0 {
		return "- (no refresh_source declared)"
	}
	var b strings.Builder
	for _, it := range items {
		b.WriteString("- ")
		b.WriteString(it)
		b.WriteString("\n")
	}
	return b.String()
}
